[package]
name = "kraken"
version = "0.1.0"
authors = ["Alex Pecsi <alex.pecsi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
